import { Fragment, useMemo, type ReactNode } from "react";

/**
 * A deliberately small Markdown renderer for the label compliance report.
 *
 * Why this exists rather than a dependency
 * ----------------------------------------
 * The app ships no Markdown library and no `dangerouslySetInnerHTML` anywhere
 * in `src/` — every string that reaches the DOM does so as a React text node.
 * Adding a general-purpose renderer to display our OWN report would import a
 * full CommonMark parser and an HTML sanitiser to solve a problem we do not
 * have: the input is generated by `buildReportMarkdown`, four lines of it, and
 * the one field that comes from outside (the model's `remarks`) is escaped at
 * the source.
 *
 * So this handles exactly the grammar that function emits, and treats
 * everything else as literal text. It builds React elements — there is no HTML
 * string anywhere in the path, so a remark containing `<script>` renders as
 * the characters `<script>` and can do nothing else.
 *
 * The grammar, in full
 * --------------------
 *   `# text`              level-1 heading
 *   `## text`             level-2 heading
 *   `- [PASS] text`       checklist item with a green PASS pill
 *   `- [FAIL] text`       checklist item with a red FAIL pill
 *   `- text`              plain bullet
 *   `**bold**`            bold, inline, anywhere above
 *   `*italic*`            italic, inline, anywhere above
 *   `\*`                  a literal asterisk
 *   blank line            paragraph break
 *   anything else         a paragraph
 *
 * Unsupported syntax is not an error. It renders as what it is: text. That is
 * the right failure mode for a document a person is reading — a stray `#` in a
 * remark should look like a `#`, not blank the section.
 */

type Props = {
  /** Markdown source, normally from `buildReportMarkdown`. */
  source: string;
  className?: string;
};

/** `- [PASS] ` / `- [FAIL] ` — the checklist marker and the rest of the line. */
const CHECK_ITEM = /^-\s\[(PASS|FAIL)\]\s+(.*)$/;

/**
 * Split a line into bold / italic / text runs.
 *
 * One pass, alternating on the delimiters, because nesting is not in the
 * grammar and pretending otherwise would mean a real parser. `\*` escapes are
 * resolved here, after matching, so an escaped asterisk can never open a run.
 */
const inline = (text: string, keyPrefix: string): ReactNode[] => {
  const nodes: ReactNode[] = [];
  // Alternation order matters: `**` must be tried before `*`.
  const pattern = /\\([*_`])|\*\*([^*]+)\*\*|\*([^*]+)\*/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  let index = 0;

  const unescape = (value: string) => value.replace(/\\([*_`])/g, "$1");

  while ((match = pattern.exec(text)) !== null) {
    if (match.index > lastIndex) {
      nodes.push(unescape(text.slice(lastIndex, match.index)));
    }
    const [, escaped, bold, italic] = match;
    if (escaped !== undefined) {
      nodes.push(escaped);
    } else if (bold !== undefined) {
      nodes.push(<strong key={`${keyPrefix}-b${index}`}>{unescape(bold)}</strong>);
    } else {
      nodes.push(<em key={`${keyPrefix}-i${index}`}>{unescape(italic)}</em>);
    }
    lastIndex = pattern.lastIndex;
    index += 1;
  }
  if (lastIndex < text.length) nodes.push(unescape(text.slice(lastIndex)));

  return nodes;
};

type Block =
  | { kind: "h1" | "h2" | "p"; text: string }
  | { kind: "list"; items: { status: "PASS" | "FAIL" | null; text: string }[] };

/** Group lines into blocks, so consecutive bullets share one `<ul>`. */
const parse = (source: string): Block[] => {
  const blocks: Block[] = [];

  for (const raw of source.split("\n")) {
    const lineText = raw.trimEnd();
    if (!lineText.trim()) continue;

    const bulletMatch = CHECK_ITEM.exec(lineText);
    const isPlainBullet = !bulletMatch && /^-\s+/.test(lineText);

    if (bulletMatch || isPlainBullet) {
      const item = bulletMatch
        ? { status: bulletMatch[1] as "PASS" | "FAIL", text: bulletMatch[2] }
        : { status: null, text: lineText.replace(/^-\s+/, "") };
      const previous = blocks[blocks.length - 1];
      if (previous?.kind === "list") previous.items.push(item);
      else blocks.push({ kind: "list", items: [item] });
      continue;
    }

    if (lineText.startsWith("## ")) {
      blocks.push({ kind: "h2", text: lineText.slice(3) });
    } else if (lineText.startsWith("# ")) {
      blocks.push({ kind: "h1", text: lineText.slice(2) });
    } else {
      blocks.push({ kind: "p", text: lineText });
    }
  }

  return blocks;
};

export default function MarkdownReport({ source, className }: Props) {
  const blocks = useMemo(() => parse(source), [source]);

  return (
    <div className={className ? `lc-md ${className}` : "lc-md"}>
      {blocks.map((block, blockIndex) => {
        const key = `b${blockIndex}`;
        if (block.kind === "h1") {
          return (
            <h2 key={key} className="lc-md-h1">
              {inline(block.text, key)}
            </h2>
          );
        }
        if (block.kind === "h2") {
          return (
            <h3 key={key} className="lc-md-h2">
              {inline(block.text, key)}
            </h3>
          );
        }
        if (block.kind === "p") {
          return (
            <p key={key} className="lc-md-p">
              {inline(block.text, key)}
            </p>
          );
        }
        return (
          <ul key={key} className="lc-md-list">
            {block.items.map((item, itemIndex) => {
              const itemKey = `${key}-i${itemIndex}`;
              return (
                <li
                  key={itemKey}
                  className={
                    item.status
                      ? `lc-md-item is-${item.status.toLowerCase()}`
                      : "lc-md-item"
                  }
                >
                  {item.status ? (
                    <span
                      className={`lc-md-status lc-md-status-${item.status.toLowerCase()}`}
                    >
                      {item.status}
                    </span>
                  ) : null}
                  <span className="lc-md-item-text">
                    {inline(item.text, itemKey)}
                  </span>
                </li>
              );
            })}
          </ul>
        );
      })}
      {blocks.length === 0 ? <Fragment /> : null}
    </div>
  );
}
