import { Fragment, useMemo, type ReactNode } from "react";

import { cn } from "@/lib/utils";

/**
 * A deliberately small Markdown renderer for the label compliance report.
 *
 * Why this exists rather than a dependency
 * ----------------------------------------
 * The app ships no Markdown library and no `dangerouslySetInnerHTML` anywhere
 * in `src/` — every string that reaches the DOM does so as a React text node.
 * Adding a general-purpose renderer to display our OWN report would import a
 * full CommonMark parser and an HTML sanitiser to solve a problem we do not
 * have: the input is generated by `buildReportMarkdown`, four lines of it, and
 * the one field that comes from outside (the model's `remarks`) is escaped at
 * the source.
 *
 * So this handles exactly the grammar that function emits, and treats
 * everything else as literal text. It builds React elements — there is no HTML
 * string anywhere in the path, so a remark containing `<script>` renders as
 * the characters `<script>` and can do nothing else.
 *
 * The grammar, in full
 * --------------------
 *   `# text`              level-1 heading
 *   `## text`             level-2 heading
 *   `- [PASS] text`       checklist item with a green PASS pill
 *   `- [FAIL] text`       checklist item with a red FAIL pill
 *   `- text`              plain bullet
 *   `**bold**`            bold, inline, anywhere above
 *   `*italic*`            italic, inline, anywhere above
 *   `\*`                  a literal asterisk
 *   blank line            paragraph break
 *   anything else         a paragraph
 *
 * Unsupported syntax is not an error. It renders as what it is: text. That is
 * the right failure mode for a document a person is reading — a stray `#` in a
 * remark should look like a `#`, not blank the section.
 *
 * ── On the conversion ─────────────────────────────────────────────────────
 * The status pills and the failing row's left rule use the label overlay's
 * literal reds and greens rather than `--color-bad` / `--color-ok`, for the
 * reason given in `LabelImage.tsx`: this report describes boxes drawn on a
 * photograph, and a pill in a different red from the box it reports is a
 * different thing on the page rather than the same thing twice.
 *
 * `data-status` carries the verdict for tests, so an assertion survives a
 * restyle — the class list is now four utilities where it was one name.
 */

type Props = {
  /** Markdown source, normally from `buildReportMarkdown`. */
  source: string;
  className?: string;
};

/** `- [PASS] ` / `- [FAIL] ` — the checklist marker and the rest of the line. */
const CHECK_ITEM = /^-\s\[(PASS|FAIL)\]\s+(.*)$/;

/**
 * Split a line into bold / italic / text runs.
 *
 * One pass, alternating on the delimiters, because nesting is not in the
 * grammar and pretending otherwise would mean a real parser. `\*` escapes are
 * resolved here, after matching, so an escaped asterisk can never open a run.
 */
const inline = (text: string, keyPrefix: string): ReactNode[] => {
  const nodes: ReactNode[] = [];
  // Alternation order matters: `**` must be tried before `*`.
  const pattern = /\\([*_`])|\*\*([^*]+)\*\*|\*([^*]+)\*/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  let index = 0;

  const unescape = (value: string) => value.replace(/\\([*_`])/g, "$1");

  while ((match = pattern.exec(text)) !== null) {
    if (match.index > lastIndex) {
      nodes.push(unescape(text.slice(lastIndex, match.index)));
    }
    const [, escaped, bold, italic] = match;
    if (escaped !== undefined) {
      nodes.push(escaped);
    } else if (bold !== undefined) {
      nodes.push(<strong key={`${keyPrefix}-b${index}`}>{unescape(bold)}</strong>);
    } else {
      nodes.push(<em key={`${keyPrefix}-i${index}`}>{unescape(italic)}</em>);
    }
    lastIndex = pattern.lastIndex;
    index += 1;
  }
  if (lastIndex < text.length) nodes.push(unescape(text.slice(lastIndex)));

  return nodes;
};

/* One member per `kind`, rather than `kind: "h1" | "h2" | "p"` on a shared one.
   A discriminant has to be a single literal for narrowing to remove the member:
   with the three folded together, ruling out "h1", "h2" and "p" in turn still
   left the text variant in play, so the `list` branch below could not see
   `items`. */
type Block =
  | { kind: "h1"; text: string }
  | { kind: "h2"; text: string }
  | { kind: "p"; text: string }
  | { kind: "list"; items: { status: "PASS" | "FAIL" | null; text: string }[] };

/** Group lines into blocks, so consecutive bullets share one `<ul>`. */
const parse = (source: string): Block[] => {
  const blocks: Block[] = [];

  for (const raw of source.split("\n")) {
    const lineText = raw.trimEnd();
    if (!lineText.trim()) continue;

    const bulletMatch = CHECK_ITEM.exec(lineText);
    const isPlainBullet = !bulletMatch && /^-\s+/.test(lineText);

    if (bulletMatch || isPlainBullet) {
      const item = bulletMatch
        ? { status: bulletMatch[1] as "PASS" | "FAIL", text: bulletMatch[2] }
        : { status: null, text: lineText.replace(/^-\s+/, "") };
      const previous = blocks[blocks.length - 1];
      if (previous?.kind === "list") previous.items.push(item);
      else blocks.push({ kind: "list", items: [item] });
      continue;
    }

    if (lineText.startsWith("## ")) {
      blocks.push({ kind: "h2", text: lineText.slice(3) });
    } else if (lineText.startsWith("# ")) {
      blocks.push({ kind: "h1", text: lineText.slice(2) });
    } else {
      blocks.push({ kind: "p", text: lineText });
    }
  }

  return blocks;
};

export default function MarkdownReport({ source, className }: Props) {
  const blocks = useMemo(() => parse(source), [source]);

  return (
    <div className={cn("text-[15.5px] leading-relaxed", className)}>
      {blocks.map((block, blockIndex) => {
        const key = `b${blockIndex}`;
        if (block.kind === "h1") {
          return (
            <h2
              key={key}
              className="m-0 mb-2.5 text-[19px] font-medium tracking-tight text-ink"
            >
              {inline(block.text, key)}
            </h2>
          );
        }
        if (block.kind === "h2") {
          return (
            <h3
              key={key}
              // The rule above a section, dropped for the first one — a
              // report should not open with a horizontal line.
              className="m-0 mb-2 mt-5 border-t-[0.5px] border-line pt-3.5 text-[16px] font-medium text-body first:mt-0 first:border-t-0 first:pt-0"
            >
              {inline(block.text, key)}
            </h3>
          );
        }
        if (block.kind === "p") {
          return (
            <p key={key} className="m-0 mb-1.5 text-body [&_strong]:font-medium [&_strong]:text-ink">
              {inline(block.text, key)}
            </p>
          );
        }
        return (
          <ul key={key} className="m-0 list-none p-0">
            {block.items.map((item, itemIndex) => {
              const itemKey = `${key}-i${itemIndex}`;
              return (
                <li
                  key={itemKey}
                  data-status={item.status ?? undefined}
                  className={cn(
                    "flex items-start gap-2.5 border-b-[0.5px] border-line py-2.5 last:border-b-0",
                    // A failed rule carries a left rule in its own colour:
                    // scannable down the page without adding a second badge to
                    // every row.
                    item.status === "FAIL" && "pl-2.5 shadow-[inset_2px_0_0_#dc2626]",
                    // A printed finding split across two pages is unreadable.
                    "print:break-inside-avoid",
                  )}
                >
                  {item.status ? (
                    <span
                      data-status={item.status}
                      className={cn(
                        "mt-px flex-none rounded-full border-[0.5px] px-2 py-0.5",
                        "text-[11.5px] font-medium tracking-wide",
                        item.status === "FAIL"
                          ? "border-danger-line bg-danger-soft text-[#b91c1c]"
                          : "border-[#bbf7d0] bg-ok-soft text-[#15803d]",
                      )}
                    >
                      {item.status}
                    </span>
                  ) : null}
                  <span className="min-w-0 text-body [&_em]:text-[0.86em] [&_em]:not-italic [&_em]:text-subtle [&_strong]:font-medium [&_strong]:text-ink">
                    {inline(item.text, itemKey)}
                  </span>
                </li>
              );
            })}
          </ul>
        );
      })}
      {blocks.length === 0 ? <Fragment /> : null}
    </div>
  );
}
