import { useEffect, useState } from "react";
import { HiCheckCircle } from "react-icons/hi2";
import DateInput from "../../components/DateInput";
import { NicField, ErrorAlert, SuccessAlert, apiErrorMessage } from "../../components/NicUI";
import {
  haisService,
  WORKING_STATUSES,
  ASSET_TYPES,
  DEPARTMENTS,
  STORAGE_TYPES,
  type Asset,
} from "../../services/haisService";

/* An empty record — every field is present so nothing is missed. */
const EMPTY: Asset = {
  asset_id: "",
  asset_type: "",
  company: "",
  model_num: "",
  serial_num: "",
  warranty_ends: "",
  processor: "",
  memory: "",
  operating_system: "",
  storage_type: "",
  storage: "",
  current_user_id: "",
  current_user_name: "",
  prev_user_id: "",
  prev_user_name: "",
  department: "",
  email_id: "",
  current_location: "",
  handover_date: "",
  purchase_invoice_no: "",
  purchase_invoice_date: "",
  amount: "",
  vendor: "",
  date_of_last_service: "",
  working_status: "Working",
  remarks: "",
};

type Props = {
  /** When set, the form loads that asset and switches to edit mode. */
  editId?: string | null;
  /** Called after a successful save so the parent can refresh / switch tabs. */
  onSaved?: (asset: Asset) => void;
};

export default function AssetForm({ editId, onSaved }: Props) {
  const [form, setForm] = useState<Asset>(EMPTY);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  // The record as loaded — lets us detect what changed (user / config) and ask why.
  const [original, setOriginal] = useState<Asset | null>(null);
  const [changeReason, setChangeReason] = useState("");

  const isEdit = !!editId;
  const userChanged =
    isEdit && (form.current_user_id ?? "").trim() !== (original?.current_user_id ?? "").trim();
  const CONFIG_KEYS: (keyof Asset)[] = ["processor", "memory", "operating_system", "storage_type", "storage"];
  const configChanged =
    isEdit && !!original && CONFIG_KEYS.some((k) => (form[k] ?? "") !== (original[k] ?? ""));

  /* Load the record when editing. */
  useEffect(() => {
    setChangeReason("");
    if (!editId) {
      setForm(EMPTY);
      setOriginal(null);
      return;
    }
    let alive = true;
    setLoading(true);
    setError("");
    haisService
      .get(editId)
      .then((data) => {
        if (!alive) return;
        setForm({ ...EMPTY, ...data });
        setOriginal(data);
      })
      .catch((err) => {
        if (alive) setError(apiErrorMessage(err));
      })
      .finally(() => {
        if (alive) setLoading(false);
      });
    return () => {
      alive = false;
    };
  }, [editId]);

  const set = (key: keyof Asset) => (value: string) =>
    setForm((f) => ({ ...f, [key]: value }));

  const save = async () => {
    setError("");
    setSuccess("");
    if (!(form.current_user_id ?? "").trim()) {
      setError("Current User ID (Emp ID) is required.");
      return;
    }
    setBusy(true);
    try {
      const payload: Asset = {
        ...form,
        asset_id: form.asset_id.trim(),
        amount: form.amount === "" ? undefined : Number(form.amount),
      };
      const saved = isEdit
        ? await haisService.update(editId!, payload, changeReason)
        : await haisService.create(payload);
      setSuccess(
        isEdit
          ? "Asset updated successfully."
          : `Asset created successfully. System-generated Asset ID: ${saved?.asset_id ?? ""}.`,
      );
      if (!isEdit) setForm(EMPTY);
      onSaved?.(saved ?? payload);
    } catch (err) {
      setError(apiErrorMessage(err));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="ofs-card ofs-card--wide">
      <div className="ofs-card-head">
        <span className="ofs-card-mark" />
        <h2>{isEdit ? `Edit Asset — ${editId}` : "Add New Asset"}</h2>
      </div>

      {loading ? (
        <p className="nic-note">Loading asset…</p>
      ) : (
        <>
          {/* ── Identification ── */}
          <h4 className="nic-subsection-title">Identification</h4>
          <div className="nic-form-grid">
            {/* Asset ID is generated by the system on Add. It is not shown on
                the Add form; when editing it appears read-only for reference. */}
            {isEdit && (
              <NicField label="Asset ID" hint="System-generated — cannot be changed">
                <input className="nic-input nic-mono" value={form.asset_id} disabled />
              </NicField>
            )}

            <NicField label="Asset Type / Category">
              <select
                className="nic-select"
                value={form.asset_type as string}
                onChange={(e) => set("asset_type")(e.target.value)}
              >
                <option value="">— Select —</option>
                {ASSET_TYPES.map((t) => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </NicField>

            <NicField label="Company" hint="Manufacturer / brand">
              <input className="nic-input" value={form.company ?? ""} onChange={(e) => set("company")(e.target.value)} placeholder="e.g. Dell, HP, Logitech" />
            </NicField>

            <NicField label="Model Number">
              <input className="nic-input" value={form.model_num ?? ""} onChange={(e) => set("model_num")(e.target.value)} placeholder="e.g. Latitude 5440" />
            </NicField>

            <NicField label="Serial Number">
              <input className="nic-input nic-mono" value={form.serial_num ?? ""} onChange={(e) => set("serial_num")(e.target.value)} placeholder="e.g. DL5440X92KK" />
            </NicField>

            <NicField label="Warranty Ends">
              <DateInput value={form.warranty_ends ?? ""} onChange={set("warranty_ends")} />
            </NicField>
          </div>

          {/* ── Configuration ── */}
          <h4 className="nic-subsection-title">Configuration</h4>
          <p className="nic-note" style={{ marginTop: -6 }}>
            For computing devices only — leave blank for peripherals like a keyboard or mouse.
          </p>
          <div className="nic-form-grid">
            <NicField label="Processor">
              <input className="nic-input" value={form.processor ?? ""} onChange={(e) => set("processor")(e.target.value)} placeholder="e.g. Intel Core i5 12th Gen" />
            </NicField>

            <NicField label="Memory (RAM)">
              <input className="nic-input" value={form.memory ?? ""} onChange={(e) => set("memory")(e.target.value)} placeholder="e.g. 16 GB" />
            </NicField>

            <NicField label="Operating System">
              <input className="nic-input" value={form.operating_system ?? ""} onChange={(e) => set("operating_system")(e.target.value)} placeholder="e.g. Windows 11 Pro" />
            </NicField>

            <NicField label="Storage Type">
              <select className="nic-select" value={form.storage_type ?? ""} onChange={(e) => set("storage_type")(e.target.value)}>
                <option value="">— Select —</option>
                {STORAGE_TYPES.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </NicField>

            <NicField label="Storage">
              <input className="nic-input" value={form.storage ?? ""} onChange={(e) => set("storage")(e.target.value)} placeholder="e.g. 512 GB" />
            </NicField>
          </div>

          {/* ── Assignment & Tracking ── */}
          <h4 className="nic-subsection-title">Assignment &amp; Tracking</h4>
          <div className="nic-form-grid">
            <NicField label="Current User ID (Emp ID) *">
              <input className="nic-input" value={form.current_user_id ?? ""} onChange={(e) => set("current_user_id")(e.target.value)} placeholder="e.g. EMP1042" />
            </NicField>

            <NicField label="Current User Name">
              <input className="nic-input" value={form.current_user_name ?? ""} onChange={(e) => set("current_user_name")(e.target.value)} />
            </NicField>

            <NicField label="Department">
              <select className="nic-select" value={form.department ?? ""} onChange={(e) => set("department")(e.target.value)}>
                <option value="">— Select —</option>
                {DEPARTMENTS.map((d) => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>
            </NicField>

            <NicField label="Email ID">
              <input className="nic-input" type="email" value={form.email_id ?? ""} onChange={(e) => set("email_id")(e.target.value)} />
            </NicField>

            <NicField label="Current Location">
              <input className="nic-input" value={form.current_location ?? ""} onChange={(e) => set("current_location")(e.target.value)} />
            </NicField>

            <NicField label="Handover Date">
              <DateInput value={form.handover_date ?? ""} onChange={set("handover_date")} />
            </NicField>

            {/* When the holder or the configuration changes while editing,
                capture WHY — it is recorded in the device's history trail. */}
            {(userChanged || configChanged) && (
              <NicField
                label={userChanged ? "Reason for handover" : "Reason for configuration change"}
                hint="Saved in the device history so the change is never lost."
                full
              >
                <input
                  className="nic-input"
                  value={changeReason}
                  onChange={(e) => setChangeReason(e.target.value)}
                  placeholder={
                    userChanged
                      ? "e.g. Previous user left / role change / laptop upgrade"
                      : "e.g. RAM upgraded 8 GB → 16 GB on user request"
                  }
                />
              </NicField>
            )}
          </div>

          {/* ── Purchase ── */}
          <h4 className="nic-subsection-title">Purchase</h4>
          <div className="nic-form-grid">
            <NicField label="Purchase Invoice No.">
              <input className="nic-input" value={form.purchase_invoice_no ?? ""} onChange={(e) => set("purchase_invoice_no")(e.target.value)} placeholder="e.g. INV-2025-8841" />
            </NicField>

            <NicField label="Purchase Invoice Date">
              <DateInput value={form.purchase_invoice_date ?? ""} onChange={set("purchase_invoice_date")} />
            </NicField>

            <NicField label="Vendor" hint="Supplier the device was bought from">
              <input className="nic-input" value={form.vendor ?? ""} onChange={(e) => set("vendor")(e.target.value)} placeholder="e.g. Computech Solutions" />
            </NicField>

            <NicField label="Amount (₹)">
              <input
                className="nic-input"
                type="number"
                min="0"
                step="0.01"
                value={form.amount as string}
                onChange={(e) => set("amount")(e.target.value)}
              />
            </NicField>
          </div>

          {/* ── Maintenance ── */}
          <h4 className="nic-subsection-title">Maintenance</h4>
          <div className="nic-form-grid">
            <NicField label="Date of Last Service">
              <DateInput value={form.date_of_last_service ?? ""} onChange={set("date_of_last_service")} />
            </NicField>

            <NicField label="Working Status">
              <select
                className="nic-select"
                value={form.working_status as string}
                onChange={(e) => set("working_status")(e.target.value)}
              >
                {WORKING_STATUSES.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </NicField>

            <NicField label="Remarks" full>
              <textarea
                className="nic-input"
                rows={2}
                value={form.remarks ?? ""}
                onChange={(e) => set("remarks")(e.target.value)}
              />
            </NicField>
          </div>

          <div className="nic-actions-row">
            <button className="ofs-primary" onClick={() => void save()} disabled={busy}>
              <HiCheckCircle style={{ verticalAlign: "-3px", marginRight: 6 }} />
              {busy ? "Saving…" : isEdit ? "Update Asset" : "Save Asset"}
            </button>
          </div>

          <ErrorAlert>{error}</ErrorAlert>
          <SuccessAlert>{success}</SuccessAlert>
        </>
      )}
    </section>
  );
}
